candidates = {
    "Doug Emhoff": {"party": "Democratic", "president": 0},
    "Kamala Harris": {"party": "Democratic", "president": 0},
    "Donald J. Trump (2nd Term)": {"party": "Republican", "president": 1},
    "Donald J. Trump (1st Term)": {"party": "Republican", "president": 1},
    "Joseph R. Biden, Jr.": {"party": "Democratic", "president": 1},
    "Tim Walz": {"party": "Democratic", "president": 0},
    "J.D. Vance": {"party": "Republican", "president": 0},
    "Nikki Haley": {"party": "Republican", "president": 0},
    "Ron DeSantis": {"party": "Republican", "president": 0},
    "Chris Christie": {"party": "Republican", "president": 0},
    "Tim Scott": {"party": "Republican", "president": 0},
    "Doug Burgum": {"party": "Republican", "president": 0},
    "Asa Hutchinson": {"party": "Republican", "president": 0},
    "Mike Pence": {"party": "Republican", "president": 0},
    "Will Hurd": {"party": "Republican", "president": 0},
    "Rudy Giuliani": {"party": "Republican", "president": 0},
    "Ben Carson": {"party": "Republican", "president": 0},
    "Pete Buttigieg": {"party": "Democratic", "president": 0},
    "Cory Booker": {"party": "Democratic", "president": 0},
    "Andrew Yang": {"party": "Democratic", "president": 0},
    "Elizabeth Warren": {"party": "Democratic", "president": 0},
    "Michael Bloomberg": {"party": "Democratic", "president": 0},
    "Hillary Clinton": {"party": "Democratic", "president": 0},
    "Barack Obama": {"party": "Democratic", "president": 1},
    "Jill Biden": {"party": "Democratic", "president": 0},
    "William J. Clinton": {"party": "Democratic", "president": 1},
    "Bernie Sanders": {"party": "Democratic", "president": 0},
    "John Kasich": {"party": "Republican", "president": 0},
    "Michael Bennet": {"party": "Democratic", "president": 0},
    "Tulsi Gabbard": {"party": "Democratic", "president": 0},
    "John Delaney": {"party": "Democratic", "president": 0},
    "Amy Klobuchar": {"party": "Democratic", "president": 0},
    "Tom Steyer": {"party": "Democratic", "president": 0},
    "Deval Patrick": {"party": "Democratic", "president": 0},
    "Julián Castro": {"party": "Democratic", "president": 0},
    "Steve Bullock": {"party": "Democratic", "president": 0},
    "Beto O'Rourke": {"party": "Democratic", "president": 0},
    "Tim Ryan": {"party": "Democratic", "president": 0},
    "Bill de Blasio": {"party": "Democratic", "president": 0},
    "Kirsten Gillibrand": {"party": "Democratic", "president": 0},
    "Jay Inslee": {"party": "Democratic", "president": 0},
    "John Hickenlooper": {"party": "Democratic", "president": 0},
    "Eric Swalwell": {"party": "Democratic", "president": 0},
    "Tim Kaine": {"party": "Democratic", "president": 0},
    "Ted Cruz": {"party": "Republican", "president": 0},
    "Scott Walker": {"party": "Republican", "president": 0},
    "Marco Rubio": {"party": "Republican", "president": 0},
    "Mitt Romney": {"party": "Republican", "president": 0},
    "Jeb Bush": {"party": "Republican", "president": 0},
    "George W. Bush": {"party": "Republican", "president": 1},
    "Mike Huckabee": {"party": "Republican", "president": 0},
    "Martin O'Malley": {"party": "Democratic", "president": 0},
    "Rick Santorum": {"party": "Republican", "president": 0},
    "Rand Paul": {"party": "Republican", "president": 0},
    "George Pataki": {"party": "Republican", "president": 0},
    "Lindsey Graham": {"party": "Republican", "president": 0},
    "Bobby Jindal": {"party": "Republican", "president": 0},
    "Lincoln Chafee": {"party": "Democratic", "president": 0},
    "Jim Webb": {"party": "Democratic", "president": 0},
    "Rick Perry": {"party": "Republican", "president": 0},
    "Carly Fiorina": {"party": "Republican", "president": 0},
    "Paul Ryan": {"party": "Republican", "president": 0},
    "Ron Paul": {"party": "Republican", "president": 0},
    "Newt Gingrich": {"party": "Republican", "president": 0},
    "Jon Huntsman": {"party": "Republican", "president": 0},
    "Michele Bachmann": {"party": "Republican", "president": 0},
    "Herman Cain": {"party": "Republican", "president": 0},
    "Tim Pawlenty": {"party": "Republican", "president": 0},
    "John McCain": {"party": "Republican", "president": 0},
    "Sarah Palin": {"party": "Republican", "president": 0},
    "Fred Thompson": {"party": "Republican", "president": 0},
    "Joseph Lieberman": {"party": "Democratic", "president": 0},
    "Albert Gore, Jr.": {"party": "Democratic", "president": 0},
    "Michelle Obama": {"party": "Democratic", "president": 0},
    "John Edwards": {"party": "Democratic", "president": 0},
    "Bill Richardson": {"party": "Democratic", "president": 0},
    "Christopher Dodd": {"party": "Democratic", "president": 0},
    "John F. Kerry": {"party": "Democratic", "president": 0},
    "Richard B. Cheney": {"party": "Republican", "president": 0},
    "Robert Dole": {"party": "Republican", "president": 0},
    "Jack Kemp": {"party": "Republican", "president": 0},
    "George Bush": {"party": "Republican", "president": 1},
    "H. Ross Perot": {"party": "Independent", "president": 0},
    "Ronald Reagan": {"party": "Republican", "president": 1},
    "Patrick J. Buchanan": {"party": "Republican", "president": 0},
    "Michael S. Dukakis": {"party": "Democratic", "president": 0},
    "Walter F. Mondale": {"party": "Democratic", "president": 0},
    "Jimmy Carter": {"party": "Democratic", "president": 1},
    "John Anderson": {"party": "Independent", "president": 0},
    "Gerald R. Ford": {"party": "Republican", "president": 1},
    "Richard Nixon": {"party": "Republican", "president": 1},
    "Hubert H. Humphrey": {"party": "Democratic", "president": 0},
    "George McGovern": {"party": "Democratic", "president": 0},
    "Barry Goldwater": {"party": "Republican", "president": 0},
    "Lyndon B. Johnson": {"party": "Democratic", "president": 1},
    "John F. Kennedy": {"party": "Democratic", "president": 1},
    "Dwight D. Eisenhower": {"party": "Republican", "president": 1},
    "Adlai Stevenson": {"party": "Democratic", "president": 0},
    "Harry S Truman": {"party": "Democratic", "president": 1},
    "John Sparkman": {"party": "Democratic", "president": 0},
    "Franklin D. Roosevelt": {"party": "Democratic", "president": 1},
    "Thomas Dewey": {"party": "Republican", "president": 0},
    "Wendell Willkie": {"party": "Republican", "president": 0},
    "Alf Landon": {"party": "Republican", "president": 0},
    "Herbert Hoover": {"party": "Republican", "president": 1},
    "Charles McNary": {"party": "Republican", "president": 0},
    "Al Smith": {"party": "Democratic", "president": 0},
    "Robert M. La Follette": {"party": "Progressive", "president": 0},
    "John W. Davis": {"party": "Democratic", "president": 0},
    "Burton K. Wheeler": {"party": "Democratic", "president": 0},
    "Calvin Coolidge": {"party": "Republican", "president": 1},
    "Warren G. Harding": {"party": "Republican", "president": 1},
    "James M. Cox": {"party": "Democratic", "president": 0},
    "William Howard Taft": {"party": "Republican", "president": 1},
    "Woodrow Wilson": {"party": "Democratic", "president": 1},
    "Theodore Roosevelt": {"party": "Republican", "president": 1},
    "William Jennings Bryan": {"party": "Democratic", "president": 0},
    "Charles E. Hughes": {"party": "Republican", "president": 0},
    "Alton B. Parker": {"party": "Democratic", "president": 0},
    "William McKinley": {"party": "Republican", "president": 1},
    "Grover Cleveland": {"party": "Democratic", "president": 1},
    "Benjamin Harrison": {"party": "Republican", "president": 1},
    "James G. Blaine": {"party": "Republican", "president": 0},
    "Abraham Lincoln": {"party": "Republican", "president": 1},
    "Ulysses S. Grant": {"party": "Republican", "president": 1}
}
